### ISSUE TITLE
When i run bee command. the error encountered: "dyld: attempt to run simulator program outside simulator (DYLD_ROOT_PATH not set)"

### ISSUE THREAD

**Issue by xiaohui-gsv** [astaxie/beego#4132] opened 2020-08-05 08:09 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.14.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
mac os catalina 10.15.4 ,6-Core Intel Core i7
go env:
![image](https://user-images.githubusercontent.com/38554198/89388595-d16cdd80-d736-11ea-9eb3-532b736dc66d.png)

3. What did you do?
I installed the Go from pkg below
![image](https://user-images.githubusercontent.com/38554198/89386673-f6ac1c80-d733-11ea-9f2c-7cbdb43a9bd0.png)
and then i used the command below to set the proxy:
```
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.io,direct
```
and then I used the command below to install the beego and bee:
```
go get -u github.com/astaxie/beego
go get -u github.com/beego/bee
```
so far so good.

4. What did you expect to see?
I want to use the bee new *** to create a project.

5. What did you see instead?
when I ran the command "bee" or "bee new ***", i encountered the error below:
![image](https://user-images.githubusercontent.com/38554198/89387955-db421100-d735-11ea-82f7-dbac619ed8ef.png)

I reboot the mac, uninstall go and re-install go and bee for 3 times, it doesn't work. can someone help me?  thanks.

**Comment by flycash** [comment] 2020-08-05 13:02
It seems that it's not bee's issue but your environment's issue. Can you execute others commands, like gofmt, goimports...

**Comment by xiaohui-gsv** [comment] 2020-08-06 02:03
yes, gofmt works fine. I didn't install goimports. 
![image](https://user-images.githubusercontent.com/38554198/89481545-8ac8c300-d7ca-11ea-9ba8-02587fee65a7.png)

I searched the error key word in Google and Bing, and got nothing. It seems like I am the only one who has this problem. what a sad story...
@flycash

**Comment by flycash** [comment] 2020-08-06 05:50
I cannot reproduce this problem. It looks like your environment misses something.  Could you clone bee's source code and then run its unit tests?

**Comment by xiaohui-gsv** [comment] 2020-08-06 06:35
@flycash  thanks for you suggestions. I will take a try. I'm a new to Go, after clone the source code, what should I do to run its unit tests?

**Comment by xiaohui-gsv** [comment] 2020-08-07 08:21
@flycash 
update: I cloned the beego/bee project. And it works in debug model. please see the screenshot below. I added a output in the first line.
<img width="1536" alt="QQ20200807-161443@2x" src="https://user-images.githubusercontent.com/38554198/89624659-25a7c700-d8c9-11ea-83af-23ddaeb4cf1c.png">

But the same error appeared when runing the project or "go run main.go".
<img width="1536" alt="22" src="https://user-images.githubusercontent.com/38554198/89624936-951db680-d8c9-11ea-8ac5-ce048bf313c0.png">

The first line I added didn't output. the error happened before main.go runing.

@flycash Any further suggestions? Thanks.

**Comment by Demolusky** [comment] 2020-08-07 09:53
@xiaohui-gsv hi, bro. Have you tried to build in bee project and create the project by the built executable file?

**Comment by xiaohui-gsv** [comment] 2020-08-07 10:23
@Demolusky yes, "go build" works fine, and generate the executable file. but launch the executable file, the same error appeared.

**Comment by flycash** [comment] 2020-08-07 14:35
![image](https://user-images.githubusercontent.com/9923838/89656471-36266480-d8fe-11ea-94df-a9fb6794d358.png)

I think the answer is in this part. The GoLang IDE add some parameter to run the test, so it works.

**Comment by Mlxa0324** [comment] 2020-08-11 09:32
@flycash

Mine is the same mistake，Don't know you solved it?

dyld: attempt to run simulator program outside simulator (DYLD_ROOT_PATH not set)
Abort trap: 6

**Comment by Mlxa0324** [comment] 2020-08-11 09:36
@xiaohui-gsv 
Mine is the same mistake，Don't know you solved it?

dyld: attempt to run simulator program outside simulator (DYLD_ROOT_PATH not set)
Abort trap: 6

**Comment by xiaohui-gsv** [comment] 2020-08-11 09:44
@Mlxa0324 not yet.

@flycash  honestly I don't know the command parameters. which parameters should I use to run the "bee ***" command?

**Comment by flycash** [comment] 2020-08-11 14:37
In general, we don't need to pass any command parameters. 
Here is a question https://stackoverflow.com/questions/51504439/what-environment-variables-control-dyld
I guess that you two installed iOS develop environment on your computer. And the computer think bee is an simulator program but actually it's not.

So the root cause is that, why bee is thought as simulator program on you computer. In face, I have iOS development environment on my computer too. But I don't get this problem.

**Comment by flycash** [comment] 2020-08-11 14:39
I think `export DYLD_ROOT_PATH=/point/to/you/dynamic lib/rootpath/ ` may  solve this problem.

**Comment by xiaohui-gsv** [comment] 2020-08-12 02:37
@flycash yes, you are correct, I have the ios develop env in my mac. 
I set the DYLD_ROOT_PATH, but another error appeared.
the DYLD_ROOT_PATH:
<img width="570" alt="QQ20200812-102933@2x" src="https://user-images.githubusercontent.com/38554198/89968588-be05c900-dc86-11ea-8afd-9993a3620b8b.png">
the error:
![image](https://user-images.githubusercontent.com/38554198/89968680-07eeaf00-dc87-11ea-9f83-699192f0d666.png)

so why the mac alway consider the bee as the simulator program? dose it need some extra configration when bee build?

**Comment by flycash** [comment] 2020-08-13 01:08
> so why the mac alway consider the bee as the simulator program? dose it need some extra configration when bee build?

Bee is a normal golang program. I cannot understand this issue.

**Comment by xiaohui-gsv** [comment] 2020-08-13 01:56
sorry, I mean why the mac always launch the bee as the simulator program?

**Comment by flycash** [comment] 2020-08-13 14:03
I don't know... Could you try to write some simple golang function and run it?

**Comment by xiaohui-gsv** [comment] 2020-08-14 01:17
yes, I created a "hello world" project, and it works well.
![image](https://user-images.githubusercontent.com/38554198/90201963-e6b8ca80-de0e-11ea-9e6c-4a634243d2e9.png)

**Comment by flycash** [comment] 2020-08-14 02:37
Let me discuss this with others. I am very confused about this issue because bee doesn't use any tricky library.

**Comment by xiaohui-gsv** [comment] 2020-08-14 03:05
cool. thanks for your patience.

**Comment by flycash** [comment] 2020-08-16 14:44
Sorry, I spent much time on it but cannot reproduce the problem. 😭

**Comment by xiaohui-gsv** [comment] 2020-08-17 05:53
that's all right. anyway thank you.

**Comment by bkbabydp** [comment] 2020-08-17 08:55
U can try "which go", and find out which version of golang u ran.

**Comment by xiaohui-gsv** [comment] 2020-08-17 09:17
@bkbabydp yeah, please see the below.
![image](https://user-images.githubusercontent.com/38554198/90379453-58ae3f80-e0ad-11ea-9de5-d6660acfe9a6.png)

**Comment by bkbabydp** [comment] 2020-08-17 09:43
how about `declare|grep -i dyld`?

**Comment by bkbabydp** [comment] 2020-08-17 09:44
how about `declare|grep -i dyld` or `env|grep -i dyld`?

**Comment by bkbabydp** [comment] 2020-08-17 09:49
and `which clang` and `which clang++`

**Comment by xiaohui-gsv** [comment] 2020-08-17 10:06
@bkbabydp please see below:
![image](https://user-images.githubusercontent.com/38554198/90384521-45eb3900-e0b4-11ea-89fb-02b836b28a91.png)

**Comment by xiaohui-gsv** [comment] 2020-08-17 10:09
so to clarify, the DYLD_ROOT_PATH wasn't set at the beginning, I set it to the MacOSX10.15.sdk path.

**Comment by bkbabydp** [comment] 2020-08-17 10:15
u set a break here: https://github.com/beego/bee/blob/develop/main.go#L37

then paste the result.

**Comment by bkbabydp** [comment] 2020-08-17 10:25
or u can try set she breaks follow the step, u will find the answers. I believe the reason is in the code of the bee.

**Comment by eyasliu** [comment] 2020-08-18 00:58
or u can try build to static execute file, try this
```sh
CGO_ENABLED=0 go get -u github.com/beego/bee
```

**Comment by bkbabydp** [comment] 2020-08-18 02:10
yep, if u wanner to find out the real reason, u can set the break; or else u just wanner to let it work, u can follow @eyasliu .

**Comment by xiaohui-gsv** [comment] 2020-08-18 02:26
@bkbabydp you can look into this reply. I had done the test using the beego/bee source code. It works well in the debug mode, but error appeared when running the project without debug mode or using the "go run main.go" or launch the exec file generated by 'go build'.
> @flycash
> update: I cloned the beego/bee project. And it works in debug mode. please see the screenshot below. I added a output in the first line.
> <img alt="QQ20200807-161443@2x" width="1536" src="https://user-images.githubusercontent.com/38554198/89624659-25a7c700-d8c9-11ea-83af-23ddaeb4cf1c.png">
> 
> But the same error appeared when runing the project or "go run main.go".
> <img alt="22" width="1536" src="https://user-images.githubusercontent.com/38554198/89624936-951db680-d8c9-11ea-8ac5-ce048bf313c0.png">
> 
> The first line I added didn't output. the error happened before main.go running.
> 
> @flycash Any further suggestions? Thanks.

**Comment by flycash** [comment] 2020-10-13 13:19
We can't reproduce this problem and we believe that this is an environment-related problem. So I close it.

**Closed by flycash** 2020-10-13 13:19 UTC
Labels: area/bee, kind/question
