### ISSUE TITLE
orm queryseter doesn't support ignore filed orm:"-"

### ISSUE THREAD

**Issue by flueg** [astaxie/beego#3820] opened 2019-10-09 14:31 UTC
go1.12.4 linux/amd64
beego develop

mysql table schema:
```
Create Table: CREATE TABLE "xphone_user" (
  "id" int(11) NOT NULL AUTO_INCREMENT,
  "uid" varchar(16) NOT NULL DEFAULT '',
  "mobile" varchar(16) NOT NULL DEFAULT '',
  "client_id" varchar(64) NOT NULL DEFAULT '',
  "user_type" int(11) NOT NULL DEFAULT '0',
  "vip_condition" tinyint(4) NOT NULL DEFAULT '0',
  "device_ttl" int(11) NOT NULL DEFAULT '0',
  "status" tinyint(4) NOT NULL DEFAULT '0',
  "register_time" datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  "ts" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  UNIQUE KEY "uid" ("uid"),
  UNIQUE KEY "mobile" ("mobile"),
  UNIQUE KEY "client_id" ("client_id")
) ENGINE=InnoDB AUTO_INCREMENT=52440 DEFAULT CHARSET=utf8
```

data definition:
```
38 type XphoneUser struct {
39 ^IId           int           `json:"-"`
40 ^IUid          string        `json:"uid"`
41 ^IMobile       string        `json:"mobile"`
42 ^IClientId     string        `json:"client_id"`
43 ^IUserType     UserTypeT     `json:"user_type"`
44 ^IVipCondition VipConditionT `json:"vip_condition"`
45 ^IDeviceTtl    int           `json:"device_ttl"`
46 ^IStatus       StatusT       `json:"status"`
47 ^IRegisterTime time.Time     `json:"register_time"`
48 ^IExpireAt     int64         `orm:"-" json:"expire_at"`
49 }
```

query statement:
```
this.GetOrm().QueryTable("xphone_user").Filter("uid", uid).One(&user)
```

error:
{"level":"info","msg":"get xphone user fail. uid:[htKbwr4RhV Error 1054: Unknown column 'T0.expire_at' in 'field list']   err:%!s(MISSING)","time":"2019-10-09T21:51:08+08:00"}

expected:
since I have declare the field ExpireAt with orm:"-", it should work.

It seems that the queryseter does not support the ignore tag orm:"-"

beego 1.12.0 doesnot have this issue.
beego 1.11.1 doesnot have this issue.

**Comment by flueg** [comment] 2019-10-10 03:08
```
this.GetOrm().QueryTable("xphone_user").Filter("uid", uid).One(&user, "uid", "mobile", "client_id", "device_ttl", "status", "register_time")
```
this works for me.

**Comment by AllenX2018** [comment] 2020-08-11 01:47
I'm trying to reproduce and solve this issue. You can assign it to me. @flycash

**Comment by AllenX2018** [comment] 2020-08-18 03:07
@flycash I cannot reproduce this issue with the latest code on develop-2.0.

**Comment by flycash** [comment] 2020-08-18 12:12
ok, I close it.

**Closed by flycash** 2020-08-18 12:12 UTC
