### ISSUE TITLE
android发送的json请求，不能接收到，1.6版本

### ISSUE THREAD

**Issue by marswj** [astaxie/beego#1573] opened 2016-01-18 07:19 UTC
ios的可以。

**Comment by astaxie** [comment] 2016-01-18 07:25
I have no idea on you description

**Comment by marswj** [comment] 2016-01-18 07:30
c++代码写的游戏。同时支持android和ios，后台beego升级到1.6版本后，android发送的post请求，beego不能识别，消息体为空。同版本ios发送的，可以接收到。是否和http请求头有关？

**Comment by astaxie** [comment] 2016-01-18 07:32
all the clients post the raw data? could you see what's request header and data from android?

**Comment by marswj** [comment] 2016-01-18 08:37
直接post的json信息

Android的：
POST /user/rank HTTP/1.1
Accept-Encoding: identity
User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.1.2; MI-ONE Plus MIUI/JMACNBF7.0)
Host: 192.168.1.188:16003
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 63


iOS的：
POST /user/rank HTTP/1.1
Host: 192.168.1.188:16003
Accept: */*
Content-Type: application/x-www-form-urlencoded
Connection: keep-alive
Cookie: xztdz_id=7246bfd9a090b07975a0c62095a4d909
User-Agent: xztdz-mobile/10 CFNetwork/758.2.8 Darwin/15.0.0
Accept-Language: zh-cn
Accept-Encoding: gzip, deflate
Content-Length: 63

**Comment by marswj** [comment] 2016-01-18 08:40
1.5版本是可以的。升级成1.6后，android就发送的请求，beego就不能获得内容了。从封包来看，客户端已经发送到服务端，不过this.Ctx.Input.RequestBody不能获得内容，是空得。

**Comment by JessonChan** [comment] 2016-01-18 08:58
@marswj the difference between android and ios is  'Accept-Encoding' header,may be i can help,but i need to know what response your client got?
paste it here,thanks

**Comment by marswj** [comment] 2016-01-18 09:04
android版本，err := json.Unmarshal(this.Ctx.Input.RequestBody, &req)，在这里已经错误了，因为是空得，没法解析请求内容了。返回的响应都是json明文，没有开启gzip那些。

**Comment by JessonChan** [comment] 2016-01-18 09:05
@marswj please,paste every thing you caught here,you can print the string(RequestBody) also.

**Comment by marswj** [comment] 2016-01-18 09:11
因为我已经又安装到1.5版本了。这个是当时的日志。如果不能看出什么，我等下重新安装下1.6

2016/01/18 14:14:01 [user.go:107][D] &{0xc820404000 0xc82000e1a0 0xc820298540 0xc82000e1c0 }
2016/01/18 14:14:01 [user.go:108][D] &{0xc820016150 0xc820012280 [] [] map[] []}
2016/01/18 14:14:01 [user.go:109][D] []
2016/01/18 14:14:01 [user.go:134][E] unexpected end of JSON input
2016/01/18 14:14:01 [router.go:825][D] | POST       | /user/rank                               | 769.077µs        | match      | /user/rank/*                             |



2016/01/18 14:14:17 [user.go:107][D] &{0xc820404000 0xc82000e1a0 0xc82041c000 0xc82000e580 }
2016/01/18 14:14:17 [user.go:108][D] &{0xc820016150 0xc820012550 [] [] map[] [123 34 115 101 114 118 101 114 34 58 49 44 34 112 108 97 116 102 111 114 109 34 58 49 44 34 116 121 112 101 34 58 49 44 34 112 97 103 101 34 58 49 44 34 115 105 103 110 34 58 34 67 67 50 51 49 67 51 57 52 56 34 125]}
2016/01/18 14:14:17 [user.go:109][D] [123 34 115 101 114 118 101 114 34 58 49 44 34 112 108 97 116 102 111 114 109 34 58 49 44 34 116 121 112 101 34 58 49 44 34 112 97 103 101 34 58 49 44 34 115 105 103 110 34 58 34 67 67 50 51 49 67 51 57 52 56 34 125]
[ORM] - 2016-01-18 14:14:17 - [Queries/default] - [  OK /    db.Query /     0.5ms] - [SELECT T0.`name` `Name`, T0.`lv` `Lv`, T0.`zhan` `Zhan`, T0.`gx` `Gx`, T0.`zhan2` `Zhan2`, T0.`petzhan` `Petzhan` FROM `user` T0 WHERE T0.`server` = ? AND T0.`platform` = ? AND T0.`islock` = ? ORDER BY T0.`lv` DESC, T0.`zhan` DESC, T0.`lastopenapptime` DESC LIMIT 30] - `1`, `1`, `0`
2016/01/18 14:14:17 [router.go:825][D] | POST       | /user/rank                               | 2.584096ms       | match      | /user/rank/*

**Comment by JessonChan** [comment] 2016-01-18 09:15
maybe it's not a bug of compress,but i still work on this issue.

**Comment by JessonChan** [comment] 2016-01-18 09:44
@marswj if you still have the problem,you may write this line in your  app.config  
CopyRequestBody=true

**Comment by marswj** [comment] 2016-01-18 10:19
@JessonChan 这个有的，不然ios发送的也不能拿到。

android客户端发送情况下的封包。因为没法解析请求json，都是返回的0或null

POST /user/upload2 HTTP/1.1
Accept-Encoding: identity
User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.1.2; MI-ONE Plus MIUI/JMACNBF7.0)
Host: 192.168.1.188:16003
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 422

{"name":"......","uid":"C15827C619A61E8FE07BB30E52E978A978D8D439","savcreatetime":"2016-01-18 13:41:48","backupuser":"","xiuclick":2,"zhanclick":0,"oreclick":0,"xiuplaytime":2880,"zhanplaytime":0,"oreplaytime":0,"gameplaytime":2880,"lv":15,"exp":87,"lglv":1,"lgexp":0,"gold":14400,"ygold":0,"usegold":0,"useygold":0,"server":1,"platform":2,"lastopenapptime":0,"zhan":0,"badman":0,"zhan2":0,"petzhan":0,"sign":"1CCDB7338A"}HTTP/1.1 200 OK
Content-Length: 109
Content-Type: application/json; charset=utf-8
Server: beegoServer:1.6.0
Set-Cookie: xztdz_id=7da59685131ef2f4ae5dbaddb216e49e; Path=/; HttpOnly
Date: Mon, 18 Jan 2016 10:22:20 GMT

{
  "islock": 0,
  "lastopenapptime": 0,
  "savold": 0,
  "zmgx": 0,
  "dizinum": 0,
  "sign": "C06334D1B4"
}POST /user/rank HTTP/1.1
Accept-Encoding: identity
User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.1.2; MI-ONE Plus MIUI/JMACNBF7.0)
Host: 192.168.1.188:16003
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 63

{"server":1,"platform":2,"type":1,"page":1,"sign":"E729E891AB"}HTTP/1.1 200 OK
Content-Length: 22
Content-Type: application/json; charset=utf-8
Server: beegoServer:1.6.0
Set-Cookie: xztdz_id=6d5df6c229d5f085e5a2cc2b52128aa3; Path=/; HttpOnly
Date: Mon, 18 Jan 2016 10:22:21 GMT

{
  "toplines": null
}

**Comment by astaxie** [comment] 2016-01-18 10:54
here is the logic for CopyBody:

```
if r.Method != "GET" && r.Method != "HEAD" {
		if BConfig.CopyRequestBody && !context.Input.IsUpload() {
			context.Input.CopyBody(BConfig.MaxMemory)
		}
		context.Input.ParseFormOrMulitForm(BConfig.MaxMemory)
	}
```

I think maybe you header make `!context.Input.IsUpload()` to true. please check it.

**Comment by marswj** [comment] 2016-01-18 11:51
不过我的http请求中并没有  multipart/form-data，很奇怪的问题。

**Comment by JessonChan** [comment] 2016-01-18 11:55
@marswj change the code in your GOPATH/src/github.com/astaxie/beego/ add some debug message yourself,i think you can locate the bug point.(you may need to delete all files in your GOPATH/pkg/github.com/astaxie/)

**Comment by astaxie** [comment] 2016-01-18 12:59
@marswj maybe you can debug in your local. https://github.com/astaxie/beego/blob/master/router.go#L659-L664

```
beego.Debug(context.Input.IsUpload())
beego.Debug(r.Method)
```

**Comment by marswj** [comment] 2016-01-18 13:01
试过了，方法是POST，能进入context.Input.CopyBody(BConfig.MaxMemory)。不过依然没用。

**Comment by astaxie** [comment] 2016-01-18 13:03
@marswj what about `BConfig.MaxMemory`

**Comment by marswj** [comment] 2016-01-18 13:07
android：
POST   post方法
CopyBody  进入CopyBody函数
67108864    MaxMemory
(0x54beb80,0xc820301c80)  input.Context.Request.Body
[0/512]0xc8203f4000  requestbody


ios：
POST
CopyBody
67108864
(0x54beb80,0xc820301e80)
[63/512]0xc8203f4200

**Comment by astaxie** [comment] 2016-01-18 13:20
it looks there's no date from android. could you print input.Context.Request.Body

**Comment by marswj** [comment] 2016-01-18 13:37
使用wireshare能看到发送给beego的json信息，不过beego没有收到。
CopyBody函数中
(0x54beb80,0xc820301c80) input.Context.Request.Body
[0/512]0xc8203f4000 requestbody

Controller中
this.Ctx.Input.RequestBody为空。

ios请求的话，是正常的。没有问题。
我回退到1.5版本，2个平台都没有问题。

**Comment by astaxie** [comment] 2016-01-18 13:42
do you have any other filters for BeforeStatic?

could you print the request.Body entry the function?https://github.com/astaxie/beego/blob/master/router.go#L601

**Comment by JessonChan** [comment] 2016-01-18 14:01
print the err in CopyBody-io.ReadAll may help

**Comment by marswj** [comment] 2016-01-18 14:36
没使用过滤器

是这么打印的不？没看出什么来。
beego.Debug
println


android:
2016/01/18 22:38:44 [router.go:601][D] in ServeHTTP
2016/01/18 22:38:44 [router.go:602][D] &{0xc8204167a0 <nil> <nil> false true {0 0} false false false}
2016/01/18 22:38:44 [router.go:662][D] POST
in CopyBody
MaxMemory= 67108864
input.Context.Request.Body= (0x54beb50,0xc820400c80)
safe= 0xc8204168a0
requestbody= [0/512]0xc8203f9e00

ios:
2016/01/18 22:39:41 [router.go:601][D] in ServeHTTP
2016/01/18 22:39:41 [router.go:602][D] &{0xc820417ac0 <nil> <nil> false true {0 0} false false false}
2016/01/18 22:39:41 [router.go:662][D] POST
in CopyBody
MaxMemory= 67108864
input.Context.Request.Body= (0x54beb50,0xc820401780)
safe= 0xc820417b60
requestbody= [63/512]0xc82042ce00

**Comment by astaxie** [comment] 2016-01-18 14:38
when you entry the ServeHTTP please print req.Body

beego.Debug(req.Body)

**Comment by JessonChan** [comment] 2016-01-18 14:40
the Android requestbody is 0/512，so err may be not nil，can you print it out？

**Comment by marswj** [comment] 2016-01-18 15:08
@astaxie 第二行就是beego.Debug(req.Body)

android：
2016/01/18 23:06:28 [router.go:601][D] in ServeHTTP
2016/01/18 23:06:28 [router.go:602][D] &{0xc82039cc80 <nil> <nil> false true {0 0} false false false}
2016/01/18 23:06:28 [router.go:662][D] POST
in CopyBody
MaxMemory= 67108864
input.Context.Request.Body= &{0xc82039cc80 <nil> <nil> false true {0 0} true false false}
safe= &{0xc820303c80 67108864}
err= <nil>
requestbody= []
2016/01/18 23:06:28 [router.go:831][D] | POST       | /user/rank                               | 606.025µs        | match      | /user/rank/*                             |

POST /user/rank HTTP/1.1
Accept-Encoding: identity
User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.1.2; MI-ONE Plus MIUI/JMACNBF7.0)
Host: 192.168.1.188:16003
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 63

{"server":1,"platform":2,"type":1,"page":1,"sign":"E729E891AB"}HTTP/1.1 200 OK
Content-Length: 22
Content-Type: application/json; charset=utf-8
Server: beegoServer:1.6.0
Set-Cookie: xztdz_id=030d075535ef6623a087e3b4c144a85f; Path=/; HttpOnly
Date: Mon, 18 Jan 2016 15:11:34 GMT

{
  "toplines": null
}



ios：
2016/01/18 23:07:03 [router.go:601][D] in ServeHTTP
2016/01/18 23:07:03 [router.go:602][D] &{0xc82039d060 <nil> <nil> false true {0 0} false false false}
2016/01/18 23:07:03 [router.go:662][D] POST
in CopyBody
MaxMemory= 67108864
input.Context.Request.Body= &{0xc82039d060 <nil> <nil> false true {0 0} false false false}
safe= &{0xc820303f80 67108864}
err= <nil>
requestbody= [123 34 115 101 114 118 101 114 34 58 49 44 34 112 108 97 116 102 111 114 109 34 58 49 44 34 116 121 112 101 34 58 49 44 34 112 97 103 101 34 58 49 44 34 115 105 103 110 34 58 34 67 67 50 51 49 67 51 57 52 56 34 125]
[ORM] - 2016-01-18 23:07:03 - [Queries/default] - [  OK /    db.Query /    43.5ms] - [SELECT T0.`name` `Name`, T0.`lv` `Lv`, T0.`zhan` `Zhan`, T0.`gx` `Gx`, T0.`zhan2` `Zhan2`, T0.`petzhan` `Petzhan` FROM `user` T0 WHERE T0.`server` = ? AND T0.`platform` = ? AND T0.`islock` = ? ORDER BY T0.`lv` DESC, T0.`zhan` DESC, T0.`lastopenapptime` DESC LIMIT 30] - `1`, `1`, `0`
2016/01/18 23:07:04 [router.go:831][D] | POST       | /user/rank                               | 47.814796ms      | match      | /user/rank/*

POST /user/rank HTTP/1.1
Host: 192.168.1.188:16003
Accept: */*
Content-Type: application/x-www-form-urlencoded
Connection: keep-alive
Cookie: xztdz_id=3f4d57385d63d6762285af709468e93a
User-Agent: xztdz-mobile/10 CFNetwork/758.2.8 Darwin/15.0.0
Accept-Language: zh-cn
Accept-Encoding: gzip, deflate
Content-Length: 63

{"server":1,"platform":1,"type":1,"page":1,"sign":"CC231C3948"}HTTP/1.1 200 OK
Content-Length: 1128
Content-Type: application/json; charset=utf-8
Server: beegoServer:1.6.0
Date: Mon, 18 Jan 2016 15:13:32 GMT

{
  "toplines": [
    {
      "Gx": 4500,
      "Lv": 26,
      "Name": "......",
      "Petzhan": 1492,
      "Zhan": 300,
      "Zhan2": 569
    },
    {
      "Gx": 1,
      "Lv": 11,
      "Name": "......",
      "Petzhan": 0,
      "Zhan": 0,
      "Zhan2": 0
    },
    {
      "Gx": 70,
      "Lv": 9,
      "Name": "......",
      "Petzhan": 0,
      "Zhan": 200,
      "Zhan2": 0
    },
    {
      "Gx": 0,
      "Lv": 8,
      "Name": "......",
      "Petzhan": 0,
      "Zhan": 0,
      "Zhan2": 0
    },
    {
      "Gx": 1,
      "Lv": 1,
      "Name": "......",
      "Petzhan": 0,
      "Zhan": 0,
      "Zhan2": 0
    },
    {
      "Gx": 0,
      "Lv": 1,
      "Name": "......",
      "Petzhan": 0,
      "Zhan": 0,
      "Zhan2": 0
    },
    {
      "Gx": 0,
      "Lv": 1,
      "Name": "......",
      "Petzhan": 0,
      "Zhan": 0,
      "Zhan2": 0
    },
    {
      "Gx": 0,
      "Lv": 1,
      "Name": "......",
      "Petzhan": 0,
      "Zhan": 0,
      "Zhan2": 10
    },
    {
      "Gx": 0,
      "Lv": 1,
      "Name": "......",
      "Petzhan": 10,
      "Zhan": 0,
      "Zhan2": 0
    }
  ]
}

**Comment by astaxie** [comment] 2016-01-18 15:11
@marswj sorry, it's my fault.

should be beego.Debug(ioutil.ReadAll(req.Body))

**Comment by marswj** [comment] 2016-01-18 15:19
第三行

2016/01/18 23:23:45 [router.go:602][D] in ServeHTTP
2016/01/18 23:23:45 [router.go:603][D] &{0xc820399080 <nil> <nil> false true {0 0} false false false}
2016/01/18 23:23:45 [router.go:604][D] [123 34 115 101 114 118 101 114 34 58 49 44 34 112 108 97 116 102 111 114 109 34 58 49 44 34 116 121 112 101 34 58 49 44 34 112 97 103 101 34 58 49 44 34 115 105 103 110 34 58 34 67 67 50 51 49 67 51 57 52 56 34 125] <nil>
2016/01/18 23:23:45 [router.go:664][D] POST
in CopyBody
MaxMemory= 67108864
input.Context.Request.Body= &{0xc820399080 <nil> <nil> false true {0 0} true false false}
safe= &{0xc8202fff80 67108864}
err= <nil>
requestbody= []
2016/01/18 23:23:45 [router.go:833][D] | POST       | /user/rank                               | 171.96µs         | match      | /user/rank/*

**Comment by astaxie** [comment] 2016-01-18 15:28
@marswj did you turnon the session? if you turn on, could you help to move these https://github.com/astaxie/beego/blob/master/router.go#L659-L664 to the https://github.com/astaxie/beego/blob/master/router.go#L643

it looks the sessionInit parse the form and read the data.

**Comment by marswj** [comment] 2016-01-19 02:23
@astaxie 
session是打开的。放到前面能正常接收到消息体。

2016/01/19 10:27:26 [router.go:602][D] in ServeHTTP
2016/01/19 10:27:26 [router.go:603][D] &{0xc820384da0 <nil> <nil> false true {0 0} false false false}
2016/01/19 10:27:26 [router.go:650][D] POST
in CopyBody
MaxMemory= 67108864
input.Context.Request.Body= &{0xc820384da0 <nil> <nil> false true {0 0} false false false}
safe= &{0xc8202e7ec0 67108864}
err= <nil>
requestbody= [123 34 115 101 114 118 101 114 34 58 49 44 34 112 108 97 116 102 111 114 109 34 58 50 44 34 116 121 112 101 34 58 49 44 34 112 97 103 101 34 58 49 44 34 115 105 103 110 34 58 34 69 55 50 57 69 56 57 49 65 66 34 125]
[ORM] - 2016-01-19 10:27:26 - [Queries/default] - [  OK /    db.Query /     0.5ms] - [SELECT T0.`name` `Name`, T0.`lv` `Lv`, T0.`zhan` `Zhan`, T0.`gx` `Gx`, T0.`zhan2` `Zhan2`, T0.`petzhan` `Petzhan` FROM `user` T0 WHERE T0.`server` = ? AND T0.`platform` = ? AND T0.`islock` = ? ORDER BY T0.`lv` DESC, T0.`zhan` DESC, T0.`lastopenapptime` DESC LIMIT 30] - `1`, `2`, `0`
2016/01/19 10:27:26 [router.go:842][D] | POST       | /user/rank                               | 1.47918ms        | match      | /user/rank/*

**Comment by astaxie** [comment] 2016-01-19 02:31
@marswj Thanks. please update the beego.it should be fixed now.

**Closed by astaxie** 2016-01-19 02:31 UTC
