### ISSUE TITLE
bee killed

### ISSUE THREAD

**Issue by starrrry** [astaxie/beego#2530] opened 2017-03-24 17:28 UTC
i do 
$ go get github.com/astaxie/beego
$ go get github.com/beego/bee
but
![2017-03-25 1 24 54](https://cloud.githubusercontent.com/assets/9651261/24305995/e0b6b24a-10f9-11e7-9514-b394e74dc904.png)

my .zshrc
![2017-03-25 1 25 20](https://cloud.githubusercontent.com/assets/9651261/24306110/5bb26d2c-10fa-11e7-88e0-b5d333dd6302.png)

what dose it mean?

**Comment by zjjott** [comment] 2017-03-27 03:05
OOM？How many memory do you have
you can run `dmesg|less` to look for Out Of Memory error

**Comment by realxu** [comment] 2017-04-04 03:56
I have the same problem.
macOS 10.12.3, go 1.7.5 darwin/amd64.

**Comment by realxu** [comment] 2017-04-04 03:58
看到解决方法了，这里关了吧
https://github.com/beego/bee/issues/403

**Comment by amrfaissal** [comment] 2017-04-04 09:16
The problem is fixed in bee's `hotfix-dlv-support` branch. Can you please give it a try to test the fix?

**Comment by starrrry** [comment] 2017-04-05 03:14
@amrfaissal thx,it works

**Closed** 2017-04-05 03:14 UTC
