### ISSUE TITLE
orm.RawSeter does not support orm.Fielder

### ISSUE THREAD

**Issue by Martinho0330** [astaxie/beego#3776] opened 2019-08-28 03:21 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.12.0

2. What operating system and processor architecture are you using (`go env`)?
1.12.1

3. What did you do?
```golang
type SharedStorage struct {
        ...
	StorageAttribute StorageAttr `orm:"column(storage_attribute);type(text)"`
}
type StorageAttr struct {
	FileSysId    string            `json:"fileSystemId"`
	StorageSize  string            `json:"storageSize"`
	MountDomain  string            `json:"mountDomain"`
	VolumeLabels map[string]string `json:"volumeLabels"`
}

var _ orm.Fielder = new(StorageAttr)

func (e *StorageAttr) String() string {
	var data []byte
	if e == nil {
		data, _ = json.Marshal(struct{}{})
	} else {
		data, _ = json.Marshal(e)
	}
	return string(data)
}

func (e *StorageAttr) FieldType() int {
	return orm.TypeTextField
}

func (e *StorageAttr) SetRaw(value interface{}) error {
	switch d := value.(type) {
	case string:
		return json.Unmarshal([]byte(d), e)
	case []byte:
		return json.Unmarshal(d, e)
	default:
		return fmt.Errorf("<JsonField.SetRaw> unknown value `%v`", value)
	}
}

func (e *StorageAttr) RawValue() interface{} {
	return e.String()
}
```

4. What did you expect to see?
orm.NewOrm().Raw("select * from dual").QueryRows(&rows)
this line of code should deserialize the StorageAttribute field with values.

5. What did you see instead?
however what I get is just an empty struct.

**Comment by AllenX2018** [comment] 2020-08-11 01:47
I'm trying to reproduce and solve this issue. You can assign it to me. @flycash

**Comment by flycash** [comment] 2020-08-11 05:19
If you can't reproduce, we can close it.

**Comment by mchtech** [comment] 2020-08-24 09:12
#4160 

Can it be backported to the next 1.12 minor release?

**Comment by flycash** [comment] 2020-08-24 14:49
@mchtech I am afraid we won't do this. But you can copy related codes and then make a PR to branch **develop**, it will be very appreciated.

**Comment by flycash** [comment] 2020-08-24 14:49
I close this issue since we have resolved it. 😄

**Closed by flycash** 2020-08-24 14:49 UTC
Labels: area/orm, status/reproduced
